### ISSUE TITLE
Standardize way of accepting arguments

### ISSUE THREAD

**Issue by akshay-edisn** [amrit2356/Dev-Training-Open-CV#1]
Please use argparse to accept arguments instead of the current method. That way, the program can be executed using a script without any user intervention.

**Comment by amrit2356** [comment]
Added the argument parser. It will take 2 inputs: input path and output path

**Comment by akshay-edisn** [comment]
There seems to be no main method. Please include a main method and pass args to it. Also, what if I don't pass input or output or both? Your code will currently fail.

**Comment by amrit2356** [comment]
I added the main method(), also put a condition branching to allow, single, both(input and output). if there is no input, it will give a standard error.
